@host=http://localhost:8080

POST {{host}}/vue-admin-template/user/login
content-type: application/json

{
    "username":"admin"
}
###
POST {{host}}/vue-admin-template/user/logout
content-type: application/json

{
    "username":"admin"
}